name: Compress n push
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  compress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compress folder
        run: |
          mkdir -p CompressedProject
          CREATIONDATE=$(date -u +%Y%m%d-%H%M%S)
          tar --exclude='./CompressedProject' --exclude='.git' --exclude='.github' \
              -czf CompressedProject/${CREATIONDATE}_youssef.tar.gz .
      - name: Logging in to AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Copying repo to S3
        run: |
         
              aws s3 cp CompressedProject/youssefwordpress.tar.gz s3://youssefappawsproject
