name: Compress n push
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  compress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Compress
        run: |
          mkdir -p CompressedProject
          tar --exclude='./CompressedProject' --exclude='.git' --exclude='.github' \
              -czf CompressedProject/youssefwordpress.tar.gz .

  Push-To-AWS:
      runs-on: ubuntu-latest
      needs: compress
      steps:
      - name: Log to AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Copy to S3
        run: |
          CREATIONDATE=$(date -u +'%Y%m%d-%H%M%S')    
          aws s3 sync . s3://youssefappawsproject/$CREATIONDATE/
