name: Compress n push
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  compress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compress folder
        run: |
          mkdir -p CompressedProject
          CREATIONDATE=$(date -u +%Y%m%d-%H%M%S)
          echo "CREATIONDATE=$CREATIONDATE" >> $GITHUB_ENV
          tar --exclude='./CompressedProject' --exclude='.git' --exclude='.github' \
              -czf CompressedProject/${CREATIONDATE}_youssef.tar.gz .
      - name: Logging in to AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Copying repo to S3
        run: aws s3 cp CompressedProject/${CREATIONDATE}_youssef.tar.gz s3://youssefappawsproject

      - name: If Tag  is Role=YoussefDeploy Deploy the update
        run: |
            aws ssm send-command \
              --targets "Key=tag:Role,Values=YoussefDeploy" \
              --document-name "AWS-RunShellScript" \
              --comment "This Github Action should deploy to any machine with the tags from above" \
              --parameters 'commands=[
                "mkdir -p /wordpressdelta",
                "aws s3 cp s3://youssefappawsproject/'${CREATIONDATE}'_youssef.tar.gz /wordpressdelta/'${CREATIONDATE}'_youssef.tar.gz",
                "mkdir -p /wordpressdelta/'${CREATIONDATE}'",
                "tar -xzf /wordpressdelta/'${CREATIONDATE}'_youssef.tar.gz -C /wordpressdelta/'${CREATIONDATE}' --overwrite",
                "mkdir /var/www/wordpress",
                "sudo chown -R www-data:www-data /var/www/wordpress",
                "sudo chmod -R 755 /var/www/wordpress",
                "sudo chmod 755 /wordpressdelta/${CREATIONDATE}/wordpress.conf",
                "rsync -a /wordpressdelta/'${CREATIONDATE}'/ /var/www/wordpress",
                "sudo mv /wordpressdelta/'${CREATIONDATE}'/wordpress.conf /etc/apache2/sites-available/wordpress.conf",
                "sudo a2ensite wordpress.conf",
                "sudo a2dissite 000-default.conf",
                "sudo a2enmod rewrite",
                "sudo systemctl reload apache2",
                "mysql -u wp_user -p password -h 10.1.0.23 -e \"CREATE USER IF NOT EXISTS '\''ReadOnlyAccess'\''@'\''%'\'' IDENTIFIED BY '\''AITechLead'\''; GRANT SELECT, INDEX, ON wordpress_db.* TO '\''ReadOnlyAccess'\''@'\''%'\''; FLUSH PRIVILEGES;\",
                "cd /var/www/wordpress/wp-content",
                "mkdir -p uploads",
                "sudo mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport fs-07ae65a185fc36bac.efs.us-east-1.amazonaws.com:/ /var/www/wordpress/wp-content/uploads",
                "echo 'fs-07ae65a185fc36bac.efs.us-east-1.amazonaws.com:/ /var/www/wordpress/wp-content/uploads nfs4 nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport,_netdev 0 0' | sudo tee -a /etc/fstab > /dev/null"
                ]'
