name: Press and Push

on:
  workflow_dispatch:

jobs:
  compress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Compress to tar
        run: |
          mkdir -p CompressedProject
          tar --exclude='./CompressedProject' --exclude='.git' --exclude='.github' \
              -czf CompressedProject/youssefwordpress.tar.gz .

  login-and-push:
    runs-on: ubuntu-latest
    needs: compress

    steps:
      - name: Checkout repo AGAIN because you wanted to go fancy and make a new step
        uses: actions/checkout@v4

      - name:  AWS cred config
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Copying  to S3
        run: |
          CREATIONDATE=$('Created at'+'%Y%m%d-%H%M%S')
          aws s3 sync . s3://youssefappawsproject/$CREATIONDATE/
